version: "3.9"
services:
  inventory_control_server:
    build: .
    image: inventory_control_server:latest
    container_name: inventory_control_server
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo_server:27017/inventory-control
    depends_on:
      - mongo_server

  mongo_server:
    image: mongo:latest
    container_name: mongo_server
    volumes:
      - ./datadir:/var/lib/mongo
    ports:
      - "27017:27017"

