name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push application
        id: docker_build_application
        uses: docker/build-push-action@v2
        with:
          context: ./inventory-control application
          file: inventory-control application/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-control-application:latest

      - name: Build and push client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: ./inventory-control client
          file: inventory-control client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-control-client:latest
          
      - id: deploy application
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-control-application:latest
          service: inventory-control
          credentials: ${{ secrets.GCP_SA_KEY }}

      - id: deploy client
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-control-client:latest
          service: inventory-control
          ccredentials: ${{ secrets.GCP_SA_KEY }}
